# Generated by Django 3.2.3 on 2021-05-30 11:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('short_description', models.TextField(verbose_name='Краткое описание ')),
                ('name_slug', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('video_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на видео ютуб')),
                ('link_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название ссылки перехода на страницу со статьей(если не указана, то статья не открывается)')),
                ('image', models.ImageField(blank=True, upload_to='blog_img/', verbose_name='Изображение превью (600 x 375)')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Статья')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
